version: 2
updates:
- package-ecosystem: mix
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: ex_doc
    versions:
    - 0.23.0
    - 0.24.0
  - dependency-name: jose
    versions:
    - 1.11.1
