language: elixir
elixir:
  - 1.7.3
otp_release:
  - 21.0.9

install:
  - mix do local.rebar --force, local.hex --force, deps.get
  - git config --global user.name "bors-ng-devdocs"
  - git config --global user.email "bors-ng-devdocs[bot]@users.noreply.github.com"

script:
  - mix run
